// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_aCUY7meJ5t44l4Ca8q9CdeVFpjju85Q',
    appId: '1:526254921868:web:39e12bea4a2eba8da183a9',
    messagingSenderId: '526254921868',
    projectId: 'project-7fef4',
    authDomain: 'project-7fef4.firebaseapp.com',
    storageBucket: 'project-7fef4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP6XMpmkrrQP8SvLZKRqOowHHhPH7sLpw',
    appId: '1:526254921868:android:332394602402981fa183a9',
    messagingSenderId: '526254921868',
    projectId: 'project-7fef4',
    storageBucket: 'project-7fef4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZbFWlizm-Rgj3h6O7Y40W2EJzIVPa85Q',
    appId: '1:526254921868:ios:bf93d1df4b1e4651a183a9',
    messagingSenderId: '526254921868',
    projectId: 'project-7fef4',
    storageBucket: 'project-7fef4.appspot.com',
    iosBundleId: 'com.example.projek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZbFWlizm-Rgj3h6O7Y40W2EJzIVPa85Q',
    appId: '1:526254921868:ios:5640472239a14401a183a9',
    messagingSenderId: '526254921868',
    projectId: 'project-7fef4',
    storageBucket: 'project-7fef4.appspot.com',
    iosBundleId: 'com.example.projek.RunnerTests',
  );
}
